[[wrfuser]]
arch = "aarch64"
git-tree-sha1 = "bad1eebaeedd516d9fd7515cb4ecacaeb21c697d"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "f71fee3c5a078466ac363a68cd6f48f86a2f7012516840b3613da55682968319"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.aarch64-linux-gnu-libgfortran3.tar.gz"
[[wrfuser]]
arch = "aarch64"
git-tree-sha1 = "0f1bb35532c4e822ccb32e390dd9b87940e703b2"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "3f122881b534d8fb8b83b71dd61b54843dffa5fe7778131a452d7b436f8acc87"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.aarch64-linux-gnu-libgfortran4.tar.gz"
[[wrfuser]]
arch = "aarch64"
git-tree-sha1 = "08563a373df9e08d773e70cd509870103bfc085c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "c665dddf1c6eea9e8f8ac2fe73ec8b55be59ab1bf39bb96604259d7e3b000d4f"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.aarch64-linux-gnu-libgfortran5.tar.gz"
[[wrfuser]]
arch = "aarch64"
git-tree-sha1 = "b5d6f6fd6188984fab3ad1aee8390773005387fd"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "4f5dadec5ccad2a8933737ddb0b1711bcd1a6487ab3c379320dd89cc8e262815"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.aarch64-linux-musl-libgfortran3.tar.gz"
[[wrfuser]]
arch = "aarch64"
git-tree-sha1 = "03050c581ec470d116511a5236889a4dcec60ad5"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "65556b8a43fd0ab8c4d8100a37fdcb2b78965a4039925e8e84c22db9d27e097a"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.aarch64-linux-musl-libgfortran4.tar.gz"
[[wrfuser]]
arch = "aarch64"
git-tree-sha1 = "4211d44cc39f84d64ebd43904360032157ebd1cd"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "1243f07989275991c8ed27696a3cfbaf6c7ff39758591e0db05cb9e009be9295"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.aarch64-linux-musl-libgfortran5.tar.gz"
[[wrfuser]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2a2534e7ac0e6cd0db9e8475a63e920c28860161"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "5fd0ece0341dfa57d2b2f3ed66966c33ff1b1eef8e9a0e0c65b5a80aa62d500a"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[wrfuser]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "55282bc5569c84317ad926725703f7aea238082e"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "6525a05dbe8ac5aac26220c93e39a3883676ced76567fe1cef1fcb8d9ded7de8"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[wrfuser]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "94104d425ce2e5207a1161343ce3c114e60aca84"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "66c3e889c2f17947c951d5e9aad6c9ea7df5a9c02b1c82d0472b006d0e70852d"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[wrfuser]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3ce369994db967f537a3701fe83124cdc5554e5a"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "081939af6ec3f39b47be73650d4d1839a34384341d261c9485edc37b1be71ff8"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[wrfuser]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b6da5c755a70310c2e9c2841a5ffd1f230098fd1"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "5b2128b7ded3234f15064f132215084ee228610a092be02e40424a7cee2a0345"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[wrfuser]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "050e10e5043a21e11549341f46f8f8db511c932c"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "9e15a89e08e414e6c68901fa720332163e60f42415c620031d35c9b07f85c9ff"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[wrfuser]]
arch = "i686"
git-tree-sha1 = "067b5224c61af9b0fe89310ea4cb0189c760e3c9"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "811a270bf6c05710b3b29b6d42704fa894067e3aa1cd912b33ee71022fca015c"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.i686-linux-gnu-libgfortran3.tar.gz"
[[wrfuser]]
arch = "i686"
git-tree-sha1 = "5c37fc9f5e70da1aecbbf3eb595e6b4355cef273"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "6926ed8d6dab92cafccfa5808338cd9e6ab9b83c4a13c1c6678e946d05c7679f"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.i686-linux-gnu-libgfortran4.tar.gz"
[[wrfuser]]
arch = "i686"
git-tree-sha1 = "d17e722a81a7408eea73ee8dcedab1d89030abc3"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "070e55fb7455c7157e43ece4793d16eb6cc90d103096d567e23df2b5209b740e"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.i686-linux-gnu-libgfortran5.tar.gz"
[[wrfuser]]
arch = "i686"
git-tree-sha1 = "e981957af08a860a1c446292ba154baf187ef3f2"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "fe87927f00ce141a1fca4627d8283cb07892e07acef984f8294a95e78cf597bf"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.i686-linux-musl-libgfortran3.tar.gz"
[[wrfuser]]
arch = "i686"
git-tree-sha1 = "d9f7e98687be02288424d18c0c963b5d6b797d83"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "8237444ddeb2e1f28ceebd3acf412ed10441dae9c6517383392a82418a789ccc"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.i686-linux-musl-libgfortran4.tar.gz"
[[wrfuser]]
arch = "i686"
git-tree-sha1 = "aaface7d7b78b361b445ca0a911b0fe5bff34cf6"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "e7ef960e3af3c5524285ef58594cefa16ebf93ff38c3d59c628133f472a09be4"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.i686-linux-musl-libgfortran5.tar.gz"
[[wrfuser]]
arch = "powerpc64le"
git-tree-sha1 = "c9730bce1784fcbb429ecc0bce84446e5770981a"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "d4a25bd948f07243d8a99e45a5791c34ed6e6cfcf8a38b9b2c6bf3fa0e5d89f6"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[wrfuser]]
arch = "powerpc64le"
git-tree-sha1 = "29ba917f72eb893df68d903d4b34ae7a8ff7b8a8"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "71e9ba0e841b43ad3ca409817dfa0a3a0b9fd7ad75d094caea0be3790c287f70"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[wrfuser]]
arch = "powerpc64le"
git-tree-sha1 = "cc963a24c65b40e8d555d3110a195020b1d3f3d3"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "ccd507ab568ab9604ac30d8ed1363c6357f1b84b0bde5d16b68b353e702a6191"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[wrfuser]]
arch = "x86_64"
git-tree-sha1 = "f06d28bdd804837c8ed563a9ee3af40e2aa3909a"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "1e5a9eee3dee4226594dff011c487c14f2446ed46da23078a0bea46197faf134"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.x86_64-linux-gnu-libgfortran3.tar.gz"
[[wrfuser]]
arch = "x86_64"
git-tree-sha1 = "113589fb1e8422dd5dd0d37d53dcf10a2e4eb691"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "fa53a1271321391d9e64c85d35bea1fd56ab9b8051ba3d86ff21ab46140efc9d"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.x86_64-linux-gnu-libgfortran4.tar.gz"
[[wrfuser]]
arch = "x86_64"
git-tree-sha1 = "4afb4300f19b77bc41452fe0cea276a0e52d02ab"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "e3ecd834858dce2601540808060bee3cea24f15cedfdc3bb73fa51f21b707552"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.x86_64-linux-gnu-libgfortran5.tar.gz"
[[wrfuser]]
arch = "x86_64"
git-tree-sha1 = "b54904d289752868e4eb75d1d3648e8f2144be4d"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "0b5f66e1f872545a83bbacb7e31c732dbc97b536702dc5110fe732801ffa8d2d"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.x86_64-linux-musl-libgfortran3.tar.gz"
[[wrfuser]]
arch = "x86_64"
git-tree-sha1 = "31df4eec7b41c2257492028c0cc4631ec312a9ed"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "520d7ddb2a920b86f8566053ed3a090a7af7477537be9d12c6e6c0023e13280a"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.x86_64-linux-musl-libgfortran4.tar.gz"
[[wrfuser]]
arch = "x86_64"
git-tree-sha1 = "33f27f2548c737f972669c3b0154ce7708cc2c93"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "b22bd7f408e6d63cde9aa64c2883490db339bcd898b228e4cda16693c3fa4d1e"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.x86_64-linux-musl-libgfortran5.tar.gz"
