[[wrfuser]]
arch = "aarch64"
git-tree-sha1 = "bad1eebaeedd516d9fd7515cb4ecacaeb21c697d"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "283a25b4fe4215f44fea1362c760d0e40b90401b6d637c0dd06ae44af1ff876d"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.aarch64-linux-gnu-libgfortran3.tar.gz"
[[wrfuser]]
arch = "aarch64"
git-tree-sha1 = "0f1bb35532c4e822ccb32e390dd9b87940e703b2"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "bd54882548ed7594e9b4edf72154b64e843130465e18ca265f26d7cb8bb3e8c9"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.aarch64-linux-gnu-libgfortran4.tar.gz"
[[wrfuser]]
arch = "aarch64"
git-tree-sha1 = "08563a373df9e08d773e70cd509870103bfc085c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "b00bf1a6ec5ac43f971abacd42fa23279b77f8a5cc0b97ab0e73e23b42570cd7"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.aarch64-linux-gnu-libgfortran5.tar.gz"
[[wrfuser]]
arch = "aarch64"
git-tree-sha1 = "b5d6f6fd6188984fab3ad1aee8390773005387fd"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "d99ebf1d82d979e752f8f452e1e4fb622d4fd652ce2675085fca57506ac42f8f"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.aarch64-linux-musl-libgfortran3.tar.gz"
[[wrfuser]]
arch = "aarch64"
git-tree-sha1 = "03050c581ec470d116511a5236889a4dcec60ad5"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "1fb1d5a2e0f0861e5081888badc92a3e48db9c22a85b5be71366f727764df29c"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.aarch64-linux-musl-libgfortran4.tar.gz"
[[wrfuser]]
arch = "aarch64"
git-tree-sha1 = "4211d44cc39f84d64ebd43904360032157ebd1cd"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "888f64442236e1141c533eb3758364a582402a77cc13428826f8c753c4c61467"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.aarch64-linux-musl-libgfortran5.tar.gz"
[[wrfuser]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2a2534e7ac0e6cd0db9e8475a63e920c28860161"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "5f26978319f6824eefb037e92095f7aefb1affdac837a359abe217feb5f9221b"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[wrfuser]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "55282bc5569c84317ad926725703f7aea238082e"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "06b2a703fe04cabfc2d01762f65955a2053abc10acacc601e3e45d71d854291b"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[wrfuser]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "94104d425ce2e5207a1161343ce3c114e60aca84"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "5329c81911e5ce93b16f8ee6af5c01dffb20cbf04a64519403290b3e24fdef51"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[wrfuser]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3ce369994db967f537a3701fe83124cdc5554e5a"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "9f71f9dfa99c11cf1446362de665a84f4f0d1d143f68175b97a571e3c66672bb"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[wrfuser]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b6da5c755a70310c2e9c2841a5ffd1f230098fd1"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "455cfc853cc58600b820b34915666ae6dc5fc178674d2b2866e5164e4f7a3fb8"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[wrfuser]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "050e10e5043a21e11549341f46f8f8db511c932c"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "472358d497ce301719de031db748b0e4bc583c2cd041243a3422ec9f49a38cbe"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[wrfuser]]
arch = "i686"
git-tree-sha1 = "067b5224c61af9b0fe89310ea4cb0189c760e3c9"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "c948097c26ca40158be053eb1e519a1b4151213fa133648847124b867db33998"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.i686-linux-gnu-libgfortran3.tar.gz"
[[wrfuser]]
arch = "i686"
git-tree-sha1 = "5c37fc9f5e70da1aecbbf3eb595e6b4355cef273"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "d5b744766d1b26073ec4fba8df901bbb63bc8193ed9bd995eaff5780ce3b005c"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.i686-linux-gnu-libgfortran4.tar.gz"
[[wrfuser]]
arch = "i686"
git-tree-sha1 = "d17e722a81a7408eea73ee8dcedab1d89030abc3"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "b38467debb28a18cba4cfc26e447d8c704107c68589c6710633fdb87df5581bd"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.i686-linux-gnu-libgfortran5.tar.gz"
[[wrfuser]]
arch = "i686"
git-tree-sha1 = "e981957af08a860a1c446292ba154baf187ef3f2"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "7f8e5cf1e6a9ee906092e2ec81e75fcb451c3568100e042921fdfc1fbc82af44"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.i686-linux-musl-libgfortran3.tar.gz"
[[wrfuser]]
arch = "i686"
git-tree-sha1 = "d9f7e98687be02288424d18c0c963b5d6b797d83"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "23b83e76347081c994b12d4cda590fe8f24114bcc1281281a52a92963c36d4a6"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.i686-linux-musl-libgfortran4.tar.gz"
[[wrfuser]]
arch = "i686"
git-tree-sha1 = "aaface7d7b78b361b445ca0a911b0fe5bff34cf6"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "4e5c3886a2f68597624d9c030d8e624aa0d34f4b93075952bc203e5eda7d6b62"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.i686-linux-musl-libgfortran5.tar.gz"
[[wrfuser]]
arch = "powerpc64le"
git-tree-sha1 = "c9730bce1784fcbb429ecc0bce84446e5770981a"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "637f41c025ebcb7a3aa76b28cad30b8986c6f9414bdf23a805bca079d31cb14f"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[wrfuser]]
arch = "powerpc64le"
git-tree-sha1 = "29ba917f72eb893df68d903d4b34ae7a8ff7b8a8"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "4e0834d4e15ded4fa0c54466aeef7078f6e6477f86959465a1d0b9629e5848a8"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[wrfuser]]
arch = "powerpc64le"
git-tree-sha1 = "cc963a24c65b40e8d555d3110a195020b1d3f3d3"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "8dd6c153c30cc9c9009475fd7e8cd8418bbc3bb6a46c081c08d9510f407e757f"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[wrfuser]]
arch = "x86_64"
git-tree-sha1 = "f06d28bdd804837c8ed563a9ee3af40e2aa3909a"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "6cbf12b71f0c505035c848a8d63e10a5df44ce32c33152e096dfdd83839ac75b"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.x86_64-linux-gnu-libgfortran3.tar.gz"
[[wrfuser]]
arch = "x86_64"
git-tree-sha1 = "113589fb1e8422dd5dd0d37d53dcf10a2e4eb691"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "066d89947438b06ec17ead7d27c9adc140e526d76e01f3a163f14f9d3876202c"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.x86_64-linux-gnu-libgfortran4.tar.gz"
[[wrfuser]]
arch = "x86_64"
git-tree-sha1 = "4afb4300f19b77bc41452fe0cea276a0e52d02ab"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "a7c00f3f874a3de46b2ea64ea0e71234bca80408244ccc0db5126d6df49b5bee"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.x86_64-linux-gnu-libgfortran5.tar.gz"
[[wrfuser]]
arch = "x86_64"
git-tree-sha1 = "b54904d289752868e4eb75d1d3648e8f2144be4d"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "839dee5cb98ee204b6776ae8d60eb8089fa6cdbc00c3b8944580fbc5fac05a34"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.x86_64-linux-musl-libgfortran3.tar.gz"
[[wrfuser]]
arch = "x86_64"
git-tree-sha1 = "31df4eec7b41c2257492028c0cc4631ec312a9ed"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "f7abbe5b00a669e6740d52915a1210b6c6e7110941c7b93b72eb2827320ef19b"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.x86_64-linux-musl-libgfortran4.tar.gz"
[[wrfuser]]
arch = "x86_64"
git-tree-sha1 = "33f27f2548c737f972669c3b0154ce7708cc2c93"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[wrfuser.download]]
    sha256 = "77eb45757709d732fca70dc0f8c32250f022b92f453dbe0549e5d206bab1e5b4"
    url = "https://github.com/freecodegaku/WRFUser_jll.jl/releases/download/wrfuser-v0.0.2+0/wrfuser.v0.0.2.x86_64-linux-musl-libgfortran5.tar.gz"
